delta lake init commit
streamnative/pulsar-io-delta-lake pull request #3
Opened 2021-10-22 02:18 UTC by frankxieke

2021-11-02 02:49 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +                log.error("getSchema from snapshot {} failed, ", startVersion, e);
Use a method to deal with get schema failed exception to avoid code duplication

2021-11-02 02:49 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +            log.info("instanceId:{} source connector do nothing, without any parition assigned",
partition

2021-11-02 02:49 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaReaderThread.java
> +                    if (startVersion == checkpoint.getSnapShotVersion()
Use `equals` instead of `==`

2021-11-02 02:49 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaReader.java
> +                ReadCursor tmp = (ReadCursor) startCursor.clone();
Can we avoid clone the cursor for each row?

2021-11-08 06:30 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +        System.out.println("map " + map + " context:" + sourceContext);
> Remove this?

yes

2021-11-08 06:34 UTC, frankxieke commented on pom.xml
> +    <pulsar.version>2.9.0-SNAPSHOT</pulsar.version>
ok, i will change to 2.8.1

2021-11-08 06:59 UTC, frankxieke commented on pom.xml
> +    <pulsar.version>2.9.0-SNAPSHOT</pulsar.version>
some context api use the latest feature, for example , sourceContext.getPulsarClient() in DeltaLakeConnectorSource. If use 2.8.1,  getPulsarClient symbol can not be found.

2021-11-08 07:00 UTC, frankxieke commented on pom.xml
> +        <version>1.10.1</version>
ok

2021-11-08 07:03 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +            log.info("enqueue : {} {} [{}] totalcount:{}", rowRecordData.nextCursor.toString(), this.destinationTopic,
yes

2021-11-08 07:13 UTC, frankxieke commented on pom.xml
> +      <version>2.6.7.1</version>
ok, i will define it in property.

2021-11-08 07:15 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +        log.info("path-> {} ", sourceContext.getClass().getProtectionDomain().getCodeSource().getLocation().getFile());
i will delete it.

2021-11-08 13:04 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +            log.info("instanceId:{} source connector do nothing, without any parition assigned",
ok

2021-11-08 13:44 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +                sourceContext.getPulsarClient().getPartitionsForTopic(sourceContext.getOutputTopic());
It seems no sync method

2021-11-09 01:45 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +            } else if (this.pulsarSchema != null) {
yes, deltaSchema is null, we will get pulsarSchema.

2021-11-09 01:47 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/parquet/ParquetReaderUtils.java
> +                cf.complete(getPargetParquetDataquetData(filePath, conf));
yes, it use a parseParquetExecutor to do parse job.

2021-11-09 01:52 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +                log.error("getSchema from snapshot {} failed, ", startVersion, e);
ok

2021-11-09 14:37 UTC, hangc0276 approved these changes

2021-11-09 14:37 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorConfig.java
> +        if (!startingTimeStamp.equals("")) {
why not use long type for timestamp?

2021-11-09 14:55 UTC, hangc0276 requested changes

2021-11-09 14:55 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaRecord.java
> +    public void fail() {
If the record send to pulsar topic failed, how do you deal with this failure and ensure message send order?

2021-11-10 00:50 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorConfig.java
> +    String s3aAccesskey;
It is a good suggestion. but source connector run on different function worker, we can not set environment values on machines. So I think config is better?

2021-11-10 01:03 UTC, frankxieke commented on pom.xml
> +    <pulsar.version>2.9.0-SNAPSHOT</pulsar.version>
ok

2021-11-10 01:25 UTC, frankxieke commented on pom.xml
> +      <version>${pulsar.version}</version>
ok

2021-11-10 01:30 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorConfig.java
> +        if (!startingTimeStamp.equals("")) {
![image](https://user-images.githubusercontent.com/2771968/141033018-52fad35c-0996-4efc-b5a7-f20645639b2d.png)
It is a little like delta api.

2021-11-10 01:48 UTC, frankxieke commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorConfig.java
> +                } catch (Exception e) {
ok

2021-11-15 02:58 UTC, hangc0276 commented on pom.xml
> +      <artifactId>delta-standalone_2.12_shade</artifactId>
delta-standalone_2.12_shade ?

2021-11-15 02:58 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +        parseParquetExecutor = Executors.newFixedThreadPool(config.parseParquetExcutorNum);
Please add thread executor name. The same blow.

2021-11-15 02:58 UTC, hangc0276 commented on src/main/java/org/apache/pulsar/ecosystem/io/deltalake/DeltaLakeConnectorSource.java
> +            log.info("processing encounter exception will stop reading record and connector will exit");
log.error ？

2021-11-17 03:51 UTC, hangc0276 approved these changes

2021-11-17 03:51 UTC, merged